# Generated by Django 3.1.6 on 2021-02-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address_1', models.CharField(blank=True, max_length=100)),
                ('address_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('zipcode', models.CharField(blank=True, max_length=5)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.IntegerField(blank=True, max_length=22)),
                ('description', models.TextField(max_length=1000)),
                ('email', models.CharField(max_length=100)),
                ('website', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
