# Generated by Django 3.1.6 on 2021-02-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=models.CharField(blank=True, max_length=22),
        ),
    ]
