# Generated by Django 3.1.6 on 2021-02-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210209_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='business',
        ),
        migrations.AddField(
            model_name='review',
            name='business',
            field=models.ManyToManyField(to='main_app.Business'),
        ),
    ]
