# Generated by Django 3.1.6 on 2021-02-10 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_auto_20210210_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('REST', 'Restaurant'), ('HAIR', 'Hair Salon'), ('BARB', 'Barber Shop'), ('ESTH', 'Esthetician'), ('NAIL', 'Nail Salon'), ('DERM', 'Dermatologist'), ('APPL', 'Appliance Repair'), ('LAWY', 'Lawyer'), ('EVEN', 'Event Planner'), ('REAL', 'Realtor'), ('SKIN', 'Skincare'), ('CLOT', 'Clothing')], default='REST', max_length=4),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=700)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
